export const DISTRICTS = [
  { name: "Colombo District", price: 290 },
  { name: "Ampara District", price: 390 },
  { name: "Anuradhapura District", price: 390 },
  { name: "Badulla District", price: 390 },
  { name: "Batticaloa District", price: 390 },
  { name: "Galle District", price: 390 },
  { name: "Gampaha District", price: 390 },
  { name: "Hambantota District", price: 390 },
  { name: "Jaffna District", price: 390 },
  { name: "Kaluthara District", price: 390 },
  { name: "Kandy District", price: 390 },
  { name: "Kegalle District", price: 390 },
  { name: "Kilinochchi District", price: 390 },
  { name: "Kurunegala District", price: 390 },
  { name: "Mannar District", price: 390 },
  { name: "Matale District", price: 390 },
  { name: "Matara District", price: 390 },
  { name: "Monaragala District", price: 390 },
  { name: "Mullaitivu District", price: 390 },
  { name: "Nuwara Eliya District", price: 390 },
  { name: "Polonnaruwa District", price: 390 },
  { name: "Puttalam District", price: 390 },
  { name: "Ratnapura District", price: 390 },
  { name: "Trincomalee District", price: 390 },
  { name: "Vavuniya District", price: 390 },
];
