export const ORDER_STATUS_PENDING = "Pending";
export const ORDER_STATUS_PROCESSING = "Processing";
export const ORDER_STATUS_PACKED = "Ready";
export const ORDER_DELIVERY_CREATED = "Delivery Created";
export const ORDER_STATUS_WAITING = "Awaiting Pickup";
export const ORDER_STATUS_OUT_DELIVERY = "Out for Delivery";
export const ORDER_STATUS_DELIVERED = "Delivered";
export const ORDER_STATUS_CANCELED = "Cancelled";

export const ORDER_STATUS = [
  ORDER_STATUS_PENDING,
  ORDER_STATUS_PROCESSING,
  ORDER_STATUS_PACKED,
  ORDER_DELIVERY_CREATED,
  ORDER_STATUS_WAITING,
  ORDER_STATUS_OUT_DELIVERY,
  ORDER_STATUS_DELIVERED,
  ORDER_STATUS_CANCELED,
];
